ResultadosDigitais/hellper

- README.md
- docs/CONFIGURING-GOOGLE.md
This PR create a section about how authorizing Requests to the Google Calendar API, adding this steps inside _CONFIGURING-GOOGLE.md_:
1. Authorizing requests to the Google Calendar API
2. Generate Google Calendar access token
3. Enabling Google Calendar API
4. Obtain your Google Calendar's ID
Follow all steps in the Google Calendar API section
After completing the instructions, you need to have the values of this enviroment variables
> Create section about Google Calendar API 

- internal/commands/open.go
- internal/model/incident.go
- internal/model/sql/postgres/repository.go
- internal/model/sql/postgres/schema/hellper.sql
This PR create a new column named commander in to hellper's database and add this column on database's controller.
On a local or staging environment, open an incident and verify if commander's column  is created with a value.
If you are going to  using the local environment for this test, first run this code on the   local database:
```
ALTER TABLE incident 
RENAME COLUMN commander TO commander_id;
```
```
ALTER TABLE incident
ADD commander_email text NULL;
```
```
DROP VIEW public.metrics;
CREATE OR REPLACE VIEW public.metrics
AS SELECT
incident.id,
incident.title,
incident.channel_id,
incident.product,
incident.team,
incident.responsibility,
incident.functionality,
incident.root_cause,
incident.severity_level,
incident.status_page_url,
incident.post_mortem_url,
incident.channel_name, …
```
> Insert the incident's commander email on database

- internal/bot/client.go
- internal/bot/client_mock.go
- internal/commands/open.go
- internal/commands/show_status.go
- internal/commands/user.go
- internal/commands/user_test.go
- internal/model/user.go
This PR creates a user.go in the command package. This new file has a function for obtaining loose user information using the user ID.
At the moment, user.go is tightly attached to the slack, as the command package is like that..
On a local or staging environment, open an incident and verify if commander's columns  is created with a value.
- commander_id
- commander_email
Hellper must be able to create the incident  without a problem and atribute a value to the commander's columns
> Create user.go in the command package

- internal/calendar/google_calendar/calendar.go
- internal/calendar/google_calendar/calendar_test.go
- internal/google_auth/auth_mock.go
- internal/handler/route.go
- internal/internal.go
Creates a function that initializes the calendar package. This initialization creates a Google Calendar Service and a logger.
When the environment starts, the service must be initialized too, without any error. But this package has no use yet.
Everything should work fine, and should not be any error log related to the calendar package.
> Initialize calendar package

- internal/commands/user_test.go
- internal/commands/util_test.go
- internal/log/zap/zap_test.go
Coverage tests was added into this PR:
**internal/commands/user_test.go**
* TestGetStringInt64
* TestGetSeverityLevelText
* TestConvertTimestamp
**internal/log/zap/zap_test.go**
* TestNewDefault
Running the follow command:
`go test -count=1 ./...`
The test should not fail
> Code coverage to user and zap

- Dockerfile
- go.sum
- internal/calendar/google_calendar/calendar.go
- internal/calendar/google_calendar/calendar_test.go
- internal/google/calendar.go
- internal/google/calendar_mock.go
- internal/internal.go
Creates a simple function that calls the Insert method, from Google Calendar, and returns an EventsInsertCall.
For testing purpose, the 3rd party Google Calendar package was moved to a google package, that interfaces the methods, enabling mocks.
No other function is currently using the created one, but it has a unit test.
Everything must work as expected.
The tests must pass.
> Hydra insert calendar event

- internal/calendar/google_calendar/calendar.go
- internal/calendar/google_calendar/calendar_test.go
Creates a private method that returns a [ConferenceSolutionKey](https://godoc.org/google.golang.org/api/calendar/v3#ConferenceSolutionKey) struct, with the Type field as "hangoutsMeet" for a Google Meet conference.
This PR only creates a private method, that no other method calls yet.
Nothing in the default behavior should change.
> Private method to create a ConferenceSolutionKey of Google Meet type

- internal/bot/client.go
- internal/bot/client_mock.go
- internal/commands/user.go
In this PR the func getUsersInConversation was added.
This function has the responsibility of only listing the users IDs within a channel.
If you want to test the function created, you can use this example:
```go
usersInConversation := getUsersInConversation(ctx, client, logger, channelID)
logger.Info(
ctx,
"command/resolve.ResolveIncidentByDialog",
log.NewValue("usersInConversation", *usersInConversation),
)
```
Example with log
```
{"level":"info","time":"2020-06-23T16:59:53.082Z","message":"command/resolve.ResolveIncidentByDialog","usersInConversation":["UT83647QV","U01030886D7"]}
```
This PR does not change any behavior.
> Adding getUsersInConversation

- internal/commands/pause_notify.go
This PR has the responsibility to pin the message on the incident channel.
Specifically in our SlackApp the scope is not configured to pin the message on the incident channel, but you can test it in your development environment.
* Deploy in staging
* Create a new incident test
* Pause the incident with command: `/staging_hellper_pause_notify` to test
Slackbot should send a message and pin it on the channel:
> Pinning the reason in the pause command

- go.sum
- internal/bot/client.go
- internal/bot/client_mock.go
- internal/commands/cancel.go
- internal/commands/close.go
- internal/commands/commands_test.go
- internal/commands/open.go
- internal/handler/events_test.go
Resolves debt #40 
This PR changes the Slack methods, that were deprecated in favor of Conversation API: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api?utm_medium=email&utm_source=newsletter&utm_campaign=fy21-Q205-changelog
Nothing should change.
Everything should work as usual.
> Conversion API migration

- internal/bot/client.go
- internal/bot/client_mock.go
- internal/commands/open.go
This PR fix the Topic Messages in channel, and adds the Commander ID into the topic of the incident channel in Slack Apps.
1. Deploy this PR in stagging or dev environment;
2. Create a incident;
3. Test if the messages are fixed in topic (Warroom, PostMortem URL and Commander)
WarRoom URL, PostMortem URL And Incident Commander will be fixed in the message topic of the incident channel.
> Hydra add incident commander inc topic

- README.md
- app.json
- internal/config/config.go
Creates a new env HELLPER_NOTIFY_ON_CANCEL, that Hellper will use to identify if it should or not notify about a canceled incident on the Product channel.
There are no tests here.
Normal behavior.
> Create env HELLPER_NOTIFY_ON_CANCEL

- internal/commands/cancel.go
- internal/handler/cancel.go
- internal/handler/route.go
Checks the status of an incident in the Hellper database before rendering the cancel dialog.
1. Change line `internal/handler/route.go:72` to `cancelHandler.ServeHTTP(w, r)`:
```go
case "cancel":
cancelHandler.ServeHTTP(w, r)
```
2. Deploy this branch on staging or local environment
3. Open an incident
4. Call `/staging_hellper_cancel`
5. Resolve the incident
6. Call `/staging_hellper_cancel` again
1. On the first time the command is called, when the incident status is `open`, the cancel dialog should render properly with the field **Description**.
2. On the second time, after the resolve command, so when the incident status is `resolved`, the cancel dialog should not appear, but instead an ephemeral message for the user.
> Check incident status before cancel

- internal/commands/cancel.go
This PR implements the verification that allows the user to notify or not the channel #incidentes-produto when an incident is being canceled. 
Also, it fixes the message pinned when the incident is canceled. Before this PR the team was not being printed correctly.
There are two possible tests. 
1. In the Staging environment set the environment variable **HELLPER_NOTIFY_ON_CANCEL** to **false**.
2. Open an Incident
3. Cancel the Incident.
In this case, only the incident channel should be notified about the canceling.
The message displayed should show the description and the team that was supporting the incident. 
1. In the Staging environment set the environment variable **HELLPER_NOTIFY_ON_CANCEL** to **true**.
2. Open an Incident
3. Cancel the Incident.
In this case, the incident channel …
> add verification on cancel notify and fix the pin message

- internal/commands/cancel.go
- internal/commands/cancel_test.go
- internal/commands/close.go
- internal/commands/open.go
- internal/commands/postmortem.go
- internal/commands/resolve.go
- internal/commands/resolve_test.go
- internal/commands/util.go
- internal/handler/cancel.go
- internal/handler/close.go
- internal/handler/open.go
- internal/handler/resolve.go
This PR adds the IncidentID in every communication (Incident Open, Resolve, Close and Cancel Status).
Besides that, I've implemented better logs with Log.trace in some funcions.
Open an incident in Staging Env, and then, resolve, closed and cancel this incident.
In every status communication (Open, Resolve, Cancel and Close) the Incident ID should appear
> Hydra add incident id to comms

- internal/bot/dialog_submission.go
- internal/commands/open.go
This PR fixes the problem presented in this issue: https://github.com/ResultadosDigitais/hellper/issues/18
This PR change the dialog at the creation of an Incident. 
Before this refactor there was no field to enter the incident title at the dialog modal. 
After this changes the user will be asked to enter not only the channel name but also the incident title name. 
1. Open an incident
The dialog modal should display a field that asks to the user to enter the incident name. 
In Addiction, the title of the PostMortem document should display the incident name instead of the channel incident name like is being shown in the image.
Finally, the title field at the postgres should be filled with the incident name and not with the channel name.
> refactor: update open dialog to show title field on open incident

- internal/commands/cancel.go
- internal/model/repository.go
- internal/model/repository_mock.go
- internal/model/sql/postgres/repository.go
Description
Use model.Incident instead of using function parameters alone, and persist the description of the cancellation in the database.
> feat: Persist incident cancelling data

- .gitignore
- Dockerfile
- cmd/notify/main.go
- entrypoint.sh
- internal/notify/channels-notify.go
- internal/notify/custom-notify.go
- internal/notify/notify.go
- internal/notify/report-notify.go
This PR is the basis for decoupling Goroutine to a k8s CronJob. This delivery allows us to make many configurations, such as, for example, notifying a slack channel, a person, generating a report and sending it by email in the future.
* CLI notify
```
$ ./notify --help
Usage of ./notify:
-msg string
A text message
-status string
[all|open|resolved]
-to string
[channel id|user id]
-type string
[channels|report|custom]
```
* We can use it into CronJob service from k8s.
```bash
git pull origin master
git checkout hydra-notify-cronjob-k8s
go build -o . ./cmd/notify
```
```bash
export HELLPER_OAUTH_TOKEN=xoxb-.....
export HELLPER_DSN=postgres://.....
```
:warning: _* You can use the staging environment variables or from your development account._
This makes it possible to send private messages …
> Notify job

- internal/commands/close.go
This PR just add a placeholder description at Team field, in incident_resolve command;
Just open and resolve a incident in Staging env;
The Placeholder at Team field into resolve command should be "Team (i.e. Mushin, Hydra, POPE)",
> add placeholder decription at close incident command team field

- internal/commands/open.go
This PR changes the max length of the IncidentTitle and ChannelName.
Just setup your environment and create a new incidente with the new max length values;
The Slack Channel should be created without problems.
> [HYDRA] Change max length of incidentTitle and ChannelName in Open Command

- catalog-info.yaml
Contexto
Estamos mapeando os componentes da RD para dentro do Backstage e por isso precisamos deste arquivo yaml no mesmo diretório do componente. Dessa forma, o componente será listado no RD Station Catalog (https://backstage.production.rdops.systems/catalog) e terá uma página na qual constarão todas as informações pertinentes tais como descrição, links, owner, relações, informações sobre CI/CD, etc.
É possível consultar mais detalhes deste mapeamento aqui: https://github.com/ResultadosDigitais/designdoc/blob/master/enablers/devtools/fonte-da-verdade-artefatos.md
> create catalog info
